[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "3e549f4f0d9b697d8f23c5963337a492357b53e8"
os = "macos"

    [[Calcium.download]]
    sha256 = "3d50bee81ad62bc21a6888ee7f442c2a89f6468df2cf54eeb6dfa65a400a6a9d"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.aarch64-apple-darwin.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "82aa17614fb9ce1308456a44e20c87adee6d8829"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "7afc6fdff22ad49033626016f677b468d026280172912aed5a1bd3a3bd4f9f10"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.aarch64-linux-gnu.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "091a42bad583e77d42b1415600cd3aeac224442e"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "93dda5f2c67afee10bece57c0d8a371debf03a3946fb5ce3519897f751fd6db7"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.aarch64-linux-musl.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4bf77c38e8f24c6fe4170538abceb9a29b71faa7"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "5a9a46602ad4fc833bda990bdb977513b9fb17b40236d81c9b594d5efd8e5241"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.armv6l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f317112f310ae57381bff17ef9090006b41625bc"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "6aaee2cfa018fcf404579843d2c63b0eb396dd5eb8ce7747e13292754bb3f152"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.armv6l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cfe0e4ba492dfff03cfcad7105c6839672c94ca1"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "844b6fe0ae1b5333da21ec0cd87f2594b3ac0569eeb289ff271f6858f8dd436e"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.armv7l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eee153ed56e80dd20c3e3adfbdd5559b6d4cbbdf"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "04b35aabc383c2baf195e8de446161fe299e9eeea8f8c50829aab1a5fad29547"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.armv7l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "acff54c77c510f3079fbea672ccf9099928200d2"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "c72cac801d3055de35edb1d25627f31d362003a5c0f2ce15e623500ace9e0d9c"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.i686-linux-gnu.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "2dc15efacd4be6e36d11ef34013e746fb6dc7db8"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "ed85341bd01763a99d263d7df5643ef52f4a148b12e2984102938d4df967dae6"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.i686-linux-musl.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "7f63c34563b9eee69af3ac17a732d4642c4e9fb4"
os = "windows"

    [[Calcium.download]]
    sha256 = "6d43801497de8c3889ab30777cce7714665a0903fe237f6b776b760f4ef63a36"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.i686-w64-mingw32.tar.gz"
[[Calcium]]
arch = "powerpc64le"
git-tree-sha1 = "6ccb682014f937bad5f4054f825d52cea6989c4c"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "b2039f76f2fed64987dd47556514e63e164a8ddac9a16009e6adcee8a2390e8e"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.powerpc64le-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "0ab5b18f7584367b3786dd18388359e425728acd"
os = "macos"

    [[Calcium.download]]
    sha256 = "ccb176a8f0d2e9eff0d6db5b08d96cbd755a72eb05322719e56c16ed05d5cfe0"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.x86_64-apple-darwin.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "496350496995529dcc011c19d0ce60d1464d5892"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "bf305c3645f51c6143dda30cfebbfe62a1f5bee5c8a066169fbdddd1a7da2316"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.x86_64-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "a379cfd520350317015e62125606f13e65053a1c"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "c492ba726e24b29e0a36908f732a0c9b131f3ca54778aa561cab14e3d3561236"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.x86_64-linux-musl.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "34baf9a194958d59a1b7b00db26e75f1c1491c2c"
os = "freebsd"

    [[Calcium.download]]
    sha256 = "52119fb24b16e946efa0e08821994e932796e4c51248706897a3ef73c607e432"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.x86_64-unknown-freebsd.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "40dcad3158b7b15525d38fc16df13eef6d045fd9"
os = "windows"

    [[Calcium.download]]
    sha256 = "993817164cb2293e64854feb8f291c103ffb1fe5081c8f1f9b5abf3c39fc96fd"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+0/Calcium.v0.400.101.x86_64-w64-mingw32.tar.gz"
