[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "c68b83511cd50d7b20cd339a0940096d15993666"
os = "macos"

    [[Calcium.download]]
    sha256 = "4231d064f955c0202ef45453301b2aac2932e6e9f6554cf1aacc17940565954f"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.aarch64-apple-darwin.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "941e844827094db39e5ce4aab9a641ee5d29073c"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "ae8b779c963bf3b38fb3f806a279d6e2dd158c602138e6f52a1054d8a1869308"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.aarch64-linux-gnu.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "93b5e05180bde653a8bf6a5b031f827e73237967"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "465292d8f0eeff2f38317a4f46b12e35d480a98521e5ea2c7636bfa8c33985be"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.aarch64-linux-musl.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2cbddf6143b1aaa5d2934b1050dfc1c90962387a"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "46668c2baeeae7cbf21d104e5351767ca61d83295128e5b0c626da780cfb9506"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.armv6l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46c49b383ad6de1b2464c05640ca98ccb9b38c85"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "078d10df87d8cc4fdb9a3b8a8ecd6a5783574ed3eafcc634cd4e18b5e36374c0"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.armv6l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "15b1c1b21c1a7abfaf565a5d417eafcd4442b58d"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "a7a7333fe264eb02cb8e18420a46d391e804c5e8d35bc84c641fd565ca4dab6c"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.armv7l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a58ff6243cc1f7aff51558f8fab8c6b0b871873a"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "0e4c18e81efed685c5497da2003a216dbb558fb2da3c4e9361f451b1913a0910"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.armv7l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "0b6b3c8b7fe8bc2b8ed5179a655c9342cd994bf2"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "2d15887ceb76e1ed4775ece6d96a3d2de975c51a93aaa8f362dfad92ec5f8261"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.i686-linux-gnu.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "6bffce441e85ceb9de78e7fceb9a067a8705e29f"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "599688c68a078954b83c4bdfaaeed92c9648624368f427a251aba517289ead55"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.i686-linux-musl.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "73a6404e04f6be107684a83e453b70c35fd9952b"
os = "windows"

    [[Calcium.download]]
    sha256 = "92801063fae78c835e496098aee7370cb3e5f4cf40fb3e8dd5acbf78c4d3bfcd"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.i686-w64-mingw32.tar.gz"
[[Calcium]]
arch = "powerpc64le"
git-tree-sha1 = "ae51ef6e8aae0d02def8a9c7ecb4fc8956d029ca"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "6c936036448da453f1fabb9aaa8a866e9477ad5248c07af9f44333135531f276"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.powerpc64le-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "24b86a0f111e1581206483569a7980142e83b2de"
os = "macos"

    [[Calcium.download]]
    sha256 = "351ebf662d956b036cb081ae419e291159aa3e35abbf1f6c4db1819d9f4e298b"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.x86_64-apple-darwin.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "a2105567bed58db58669228f59e0f1bac76db888"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "edb95d0db553eaabdc674275233ca7d3d09376580459c7bcc4439a850ef95002"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.x86_64-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "2062b25cd26859b1e4d456ed9461f19cad6a44a4"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "6b85f7455d1c353bede435f3047c861f5ef280dbfb3bc858e4ecab0773ae1819"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.x86_64-linux-musl.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "aaf9dde81dc6dadefb8f9634e24e6039f0fb545a"
os = "freebsd"

    [[Calcium.download]]
    sha256 = "dc65fca8839bde3fc1254da853df4771d3c1fa24b79e58291f10e81c7c70cd99"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.x86_64-unknown-freebsd.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "04688088c4c535af69cef9e29a938b7e66bd89cf"
os = "windows"

    [[Calcium.download]]
    sha256 = "ba75dbd823b4c7cbface4e852cee02f09ee6a9c48f7eb2da35ee5eeb543b6070"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.101+1/Calcium.v0.400.101.x86_64-w64-mingw32.tar.gz"
