[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "25cdad53c674f25a1b88bde3ae467bd13315e40b"
os = "macos"

    [[Calcium.download]]
    sha256 = "f548dfa951cfc39c696956de915093f875470ce300091cfcdbff5099ce60d38a"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.aarch64-apple-darwin.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "061f6b4d9f05f232d833fb78b260b5d604d20917"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "80e0d860072125434b5f5a821deaebf30f449391c3411b1d1cdc7d8dbff77e9c"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.aarch64-linux-gnu.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "d1f69d65bc8ca93454cd961cd1ab0b2f7b988def"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "4c964208ea50373d865e0f3236acd096469e4334152d6a46ae86a580e0f54344"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.aarch64-linux-musl.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b64c9475683fcf0a585f34fc2cd5e19eb1374c8"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "657e5a62034968e16b3dda6eaa8c8519c3eae7028fdc05ad60cdf4e5eb10bfd6"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.armv6l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c59c506d053ae3c2999d62aa24a4f9001f4e73f4"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "b7f155943f803037cd2439969b2ddb32b24d98c81b4a887cfb38076f0e04262d"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.armv6l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "24cfc0beed284ddc93c544c1e154e5770d9859b5"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "3f2c5eb3a8de81fc10c34628a7ecaba6875df9c713fce09985e1308f0b6e356e"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.armv7l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e3909744946f3538af4a9cbd1d2c60b5488273b"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "87490e0b005e06fa3097a48e3fd2b3b568160ff0c6603ba24d8343a855198fc7"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.armv7l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "ac3cf2bcc551139c4174b2f4ffbbdeac6d1fd249"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "a34f5ca8ade5604555a1884999b81c3f510b91f7eed4af417e1fa9cca6adacec"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.i686-linux-gnu.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "29e35c537ddc922ba4c35c44285c4a0e1e21e557"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "4884faf9096c852dbd48863a05508e329658096e81ee3077f74a3b1aa7a1e148"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.i686-linux-musl.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "0fbb7147847df19cbad0f4783a7f5cd54ff26b09"
os = "windows"

    [[Calcium.download]]
    sha256 = "ceaa98b333391c0a1d821af76f1548cd21ecbd39926d41a241af76ba124f2518"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.i686-w64-mingw32.tar.gz"
[[Calcium]]
arch = "powerpc64le"
git-tree-sha1 = "c67ebf9fa73e5894129a144ad03ba19d0bd47419"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "85fe9592441457eede35e979165db2f59952c0c44eb2139197b010422c28f867"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.powerpc64le-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "4910d0edce0ba77e149f0bfbd2e377a9c4be9581"
os = "macos"

    [[Calcium.download]]
    sha256 = "02e424a2cb142a9075e39aa085d5e9f83c8effaace3f5a6feb9b3a015ea5994b"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.x86_64-apple-darwin.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "bc6c82116258a0859b043ea4536d6f6cd78b35c7"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "a9a2252eb4e9a0f961fe733b6ad78cebb5c878b88882ebbde6df2d4fb19f59ff"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.x86_64-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "b2a03ac7bb2f835a18861b9c5ccc504ca3a2ec57"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "d898b09d07f55c2f24fabbc3d45025ca2bb9e02b53db320ab5bc5882e6e4c55e"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.x86_64-linux-musl.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "1a828a7a27890ada5d708cb66778754109f5ff04"
os = "freebsd"

    [[Calcium.download]]
    sha256 = "310b35a4f6297bf13f2fb96020c850474bbe4855f0f37bbc70dd338999f7ee8d"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.x86_64-unknown-freebsd.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "7f3a6609275cfc4e65882e4926c26aa99aabdb8b"
os = "windows"

    [[Calcium.download]]
    sha256 = "2be7131649f15a079166aaf2dc71828abfb7a0577a93adcc6ef14a9ede6af4d3"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.102+0/Calcium.v0.400.102.x86_64-w64-mingw32.tar.gz"
