[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "0490120658e9bbbf10db5fa0a06a573509942578"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "f8ae7ba98a13d4305634ca96adc98523505efe525706f44255345f3e17f8fee3"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.aarch64-linux-gnu.tar.gz"
[[Calcium]]
arch = "aarch64"
git-tree-sha1 = "543f4c1e999f9e2a2050e60a9aacb74f78ff5b81"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "33e5fe8d6bd78abca275b7b2c2c89000c00e1aade8ea872f9a670fdab0727e2d"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.aarch64-linux-musl.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81039e376d143c60627670d149522fd05111c8c8"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "d618a6110c28e04143afb56640c132cf4e1b40a7f7b245e00b4f37b1a12e6f44"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.armv7l-linux-gnueabihf.tar.gz"
[[Calcium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bbf0b4364214859c2e9c0eb5c6f3c32fa3f5b523"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "ca9f70d649f04c4be6466e9b934e41ed0a154de31f2b961a807b4485c9372a56"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.armv7l-linux-musleabihf.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "a824e325f9cf210f5bd74f9e379d4695aa9a274f"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "298dd9e8d6c214f10d4991971161ff2deb8cc0e9419102b2ea08e407a9bebac7"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.i686-linux-gnu.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "cb92934b31074862d2e0f83d532be0886be23776"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "b673869a807e84487164e8f7d7bae700611a915d34c25ec1eae875d96910b180"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.i686-linux-musl.tar.gz"
[[Calcium]]
arch = "i686"
git-tree-sha1 = "34c87b12150a700daeeac556b86a478cd03e0eb1"
os = "windows"

    [[Calcium.download]]
    sha256 = "97f0b57a22c5070ebbe75faec7bf05a24dee0fb007123b53aaf6b977a67de5d8"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.i686-w64-mingw32.tar.gz"
[[Calcium]]
arch = "powerpc64le"
git-tree-sha1 = "7022a0b281e437155615fbe7ef25305159fa86f9"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "c3d1e07c76f9edabcc0763963ccc152128f19ff8b8d61de4b20da07d6c9b76ac"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.powerpc64le-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "b262bb4a68a3a48687956327ff0760efb0c18df2"
os = "macos"

    [[Calcium.download]]
    sha256 = "4520c75c0c784916f24d6fe02f529f3eb9f17ee2d85934ca1a9aa0212819ed89"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.x86_64-apple-darwin.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "8300d024bd945f326eeb38347b82b7793522d119"
libc = "glibc"
os = "linux"

    [[Calcium.download]]
    sha256 = "fa7f674fdf11581d635650f6d01a847cdaf518f8807c97810538432493e4bcd3"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.x86_64-linux-gnu.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "273f356c0e84d73581da50d445a1bc1ee9942b31"
libc = "musl"
os = "linux"

    [[Calcium.download]]
    sha256 = "b7edb7b9c7e321907ee485e849d92b2765701eb61a301cff85400fca5550798c"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.x86_64-linux-musl.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "4be578edcc4e460d8dd5354b8ee8ccafd85893e1"
os = "freebsd"

    [[Calcium.download]]
    sha256 = "5b24d00a64af0713687d1ea5d9dc951386c0e78f48811cd58d9f51802feefbf5"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.x86_64-unknown-freebsd.tar.gz"
[[Calcium]]
arch = "x86_64"
git-tree-sha1 = "5c84f5157dc3507fcdf05c9027ca9626a2c5eefa"
os = "windows"

    [[Calcium.download]]
    sha256 = "6f39cc7348cd9f845e6b4b865fa338570fcc9cb55e263166581fed209c3bfeb6"
    url = "https://github.com/JuliaBinaryWrappers/Calcium_jll.jl/releases/download/Calcium-v0.400.100+0/Calcium.v0.400.100.x86_64-w64-mingw32.tar.gz"
